"""initial

Revision ID: 5a360645121d
Revises: 
Create Date: 2026-05-20 16:05:52.883278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a360645121d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('arrival_config_json', sa.Text(), nullable=False),
    sa.Column('default_algorithm', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['layout_id'], ['layouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('tick_step_ms', sa.Integer(), nullable=False),
    sa.Column('max_ticks', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('event_log_checksum', sa.String(length=64), nullable=True),
    sa.Column('avg_wait_ticks', sa.Float(), nullable=False),
    sa.Column('max_wait_ticks', sa.Integer(), nullable=False),
    sa.Column('throughput_per_100_ticks', sa.Float(), nullable=False),
    sa.Column('total_stops', sa.Integer(), nullable=False),
    sa.Column('pct_null_control', sa.Float(), nullable=False),
    sa.Column('vehicles_passed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('event_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id_fk', sa.String(length=32), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id_fk'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('snapshots_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recordings')
    op.drop_table('event_records')
    op.drop_table('runs')
    op.drop_table('scenarios')
    op.drop_table('layouts')
    # ### end Alembic commands ###
